FORM_QUESTION_LABELS: dict[str, str] = {
    "1": "Nombre real, WhatsApp y email principal",
    "2": "¿El negocio es propio o de un cliente?",
    "3": "¿Con cuál rol te identificás más?",
    "4": "Links de redes activas",
    "5": "¿Cuál es exactamente tu oferta?",
    "6": "¿En qué nicho operás y qué te diferencia?",
    "7": "¿A quién le hablás? Avatar",
    "8": "¿A qué precio vendés?",
    "9": "¿Dónde creás contenido y cuál trae leads más calificados?",
    "10": "¿Trabajás con calendario de contenido planificado?",
    "11": "¿Tomás decisiones en base a métricas o percepción?",
    "12": "¿Cuántos chats abrís por mes y por qué vía?",
    "13": "¿Cuánto facturaste en los últimos 6 meses?",
    "14": "¿Qué porcentaje de chats agenda llamada y asiste?",
    "15": "¿Cuál es tu tasa de cierre?",
    "16": "¿Contás con un funnel de conversión?",
    "17": "¿Bajo qué criterio filtrás leads?",
    "18": "¿Tenés proceso de seguimiento para leads que no compran?",
    "19": "¿Qué herramientas usás para operar el negocio?",
    "20": "¿Quiénes integran tu equipo y qué función cumple cada uno?",
    "21": "¿Quién toma las decisiones?",
    "22": "¿Qué incluye exactamente tu programa o servicio?",
    "23": "¿Cuántos clientes activos tenés y cómo medís su progreso?",
    "24": "¿Contás con sistema de upsell y recompra?",
    "25": "¿A cuántos clientes más podrías atender sin cambios?",
    "26": "¿Qué experiencia atraviesa el cliente desde que compra?",
    "27": "Mejores casos de éxito",
    "28": "¿Qué probaste antes de ATV y por qué no funcionó?",
    "29": "3 problemas principales para escalar hoy",
    "30": "¿Cuál es el principal freno de tu negocio?",
    "31": "Objetivo concreto a 4 meses",
    "32": "¿Por dónde me conociste?",
    "33": "¿Qué formato de contenido te aporta más?",
    "34": "¿Por qué elegiste ese formato?",
    "35": "¿Qué tipo de Reels te gustan más?",
    "36": "¿Qué hace que te gusten esos Reels?",
    "37": "¿Qué tipo de videos de YouTube te gustan más?",
    "38": "¿Qué hace que te gusten los videos de YouTube?",
    "39": "¿Qué te gusta o aporta más de las Historias?",
    "40": "¿Qué te hizo finalmente decir SÍ y entrar a ATV?",
    "41": "¿Qué te motivó específicamente a tomar acción?",
    "42": "¿Cuánto tiempo tardaste en decidirte?",
    "43": "¿Qué podría haber funcionado mejor para decidirte antes?",
    "44": "¿Qué aspecto se podría mejorar?",
    "45": "Nivel de convicción antes de la llamada (1-10)",
    "46": "¿Qué fue lo último que te convenció?",
    "47": "¿Qué impedía que compres?",
    "48": "¿Qué programa compraste?",
    "49": "¿Algo dentro de ATV que si lo hubieras visto antes habría ayudado?",
}

LEGACY_FORM_LABELS: dict[str, str] = {
    "nombre": "Nombre completo y/o canal de Discord",
    "perfil": "Perfil",
    "nicho": "Nicho o industria",
    "oferta": "Oferta",
    "precio": "Precio de la oferta principal",
    "cliente_ideal": "Cliente ideal",
    "facturacion_actual": "Facturación actual",
    "meta_90": "Meta de facturación (90 días)",
    "activos": "Activos en el negocio",
    "objetivo": "Objetivo principal",
    "obstaculos": "Obstáculos",
    "extra": "Información adicional",
}
